name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup clj-kondo
      uses: DeLaGuardo/setup-clj-kondo@v1
    - name: Install dependencies
      run: lein deps
    - name: Lint (clj-kondo)
      run: clj-kondo --lint "$(lein classpath)" 
    - name: Lint (eastwood)
      run: lein eastwood
    - name: Run tests
      run: lein test
