name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DeLaGuardo/setup-clj-kondo@v1
      with:
        version: '2020.04.05'
    - name: Install dependencies
      run: lein deps
    - name: Lint (clj-kondo)
      run: clj-kondo --lint src
    - name: Lint (eastwood)
      run: lein eastwood
    - name: Run tests
      run: lein kaocha
    - name: Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: lein deploy github
    - name: Uberjar
      run: lein uberjar
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: charon
        path: target/uberjar/charon-*-standalone.jar
