name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Lint (clj-kondo)
      uses: DeLaGuardo/clojure-lint-action@master
      with:
        clj-kondo-args: --lint "$(lein classpath)"
        check-name: clj-kondo
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Lint (eastwood)
      run: lein eastwood
    - name: Run tests
      run: lein test
